{
 "title": "Kafka Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Messages in Time Interval",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "diff",
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\", topic=\"\"})"
    }
   ]
  },
  {
   "title": "Total Produce Requests Time Interval",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "diff",
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_Count{name=\"TotalProduceRequestsPerSec\", topic=\"\"})"
    }
   ]
  },
  {
   "title": "Total Bytes In in Time Interval",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "decbytes",
   "valueName": "diff",
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\", topic=\"\"})"
    }
   ]
  },
  {
   "title": "Total Fetch Requests Time Interval",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "diff",
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_Count{name=\"TotalFetchRequestsPerSec\", topic=\"\"})"
    }
   ]
  },
  {
   "title": "Total Bytes Out in Time Interval",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "decbytes",
   "valueName": "diff",
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\", topic=\"\"})"
    }
   ]
  },
  {
   "title": "Partiton Leader Count per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"LeaderCount\"}",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  },
  {
   "title": "Replica Count per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"PartitionCount\"}",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  },
  {
   "title": "Total Partitons Leader Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{name=\"LeaderCount\"})",
     "legendFormat": "Total Partitions"
    }
   ]
  },
  {
   "title": "Total Replica Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{name=\"PartitionCount\"})",
     "legendFormat": "Total Replicas"
    }
   ]
  },
  {
   "title": "Messages In per Second per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\", topic=\"\"}[2m])",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  },
  {
   "title": "Total Messages In per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\", topic=\"\"}[2m]))",
     "legendFormat": "Total Messages In"
    }
   ]
  },
  {
   "title": "Bytes In per Broker per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\", topic=\"\"}[2m])",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  },
  {
   "title": "Total Bytes In per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\", topic=\"\"}[2m]))",
     "legendFormat": "Total Bytes In"
    }
   ]
  },
  {
   "title": "Replication Bytes In per Broker per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_Count{name=\"ReplicationBytesInPerSec\", topic=\"\"}[2m])",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  },
  {
   "title": "Total Replication Bytes In per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"ReplicationBytesInPerSec\", topic=\"\"}[2m]))",
     "legendFormat": "Total Bytes In"
    }
   ]
  },
  {
   "title": "Bytes Out per Second per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\", topic=\"\"}[2m])",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  },
  {
   "title": "Total Bytes Out per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\", topic=\"\"}[2m]))",
     "legendFormat": "Total Bytes Out"
    }
   ]
  },
  {
   "title": "Replication Bytes Out per Second per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_Count{name=\"ReplicationBytesOutPerSec\", topic=\"\"}[2m])",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  },
  {
   "title": "Total Replication Bytes Out per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"ReplicationBytesOutPerSec\", topic=\"\"}[2m]))",
     "legendFormat": "Total Bytes Out"
    }
   ]
  },
  {
   "title": "Fetch Request Rate per Second per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_Count{name=\"TotalFetchRequestsPerSec\", topic=\"\"}[2m])",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  },
  {
   "title": "Total Fetch Request Rate per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"TotalFetchRequestsPerSec\", topic=\"\"}[2m]))",
     "legendFormat": "Total Fetch Request Rate"
    }
   ]
  },
  {
   "title": "Produce Request Rate per Second per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_Count{name=\"TotalProduceRequestsPerSec\", topic=\"\"}[2m])",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  },
  {
   "title": "Total Produce Request Rate per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"TotalProduceRequestsPerSec\", topic=\"\"}[2m]))",
     "legendFormat": "Total Fetch Request Rate"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Rate per Second per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_Count{name=\"FailedFetchRequestsPerSec\", topic=\"\"}[1m])",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  },
  {
   "title": "Failed Produce Request Rate per Second per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_Count{name=\"FailedProduceRequestsPerSec\", topic=\"\"}[1m])",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  },
  {
   "title": "Bytes Rejected per Second per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesRejectedPerSec\", topic=\"\"}[1m])",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  }
 ]
}