{
 "title": "Kafka Topics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Message Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max(kafka_log_Log_Value{name=\"LogEndOffset\"}-on(node_target,topic,partition)kafka_log_Log_Value{name=\"LogStartOffset\"})by(topic,partition))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message Rate (Input)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\", topic!=\"\"}[2m]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes/sec (Input)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\", topic!=\"\"}[2m]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes/sec (Output)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\", topic!=\"\"}[2m]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}