{
 "title": "Kafka Status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Failed Requests",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(increase(kafka_network_RequestMetrics_Count{name=\"ErrorsPerSec\",error!=\"NONE\"}[15m])) or vector(1))"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (request,error) (increase(kafka_network_RequestMetrics_Count{name=\"ErrorsPerSec\",error!=\"NONE\"}[1m]))",
     "legendFormat": "{{request}}-{{error}}"
    }
   ]
  },
  {
   "title": "Under MinIsr",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{name=\"UnderMinIsrPartitionCount\"})"
    }
   ]
  },
  {
   "title": "UnderMinIsr",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"UnderMinIsrPartitionCount\"}",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "clamp_max(sum(sum_over_time(kafka_server_ReplicaManager_Value{name=\"UnderReplicatedPartitions\"}[15m])),1) or vector(1)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"UnderReplicatedPartitions\"}",
     "legendFormat": "{{instance_group}}-{{instance_number}}"
    }
   ]
  }
 ]
}